Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import login_view, logout_view,register_view, profile_create

urlpatterns = [
    path('', include('realEstate.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('login/',login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register_view, name="register"),
    path('profile/', profile_create, name="profile"),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog/realEstate/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse


# Create your models here.
class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField(max_length=160)
    address = models.TextField(max_length=50)
    featured = models.BooleanField(blank=True, null=True)
    phone_number = models.CharField(blank= True, verbose_name='Phone Number', null=True, max_length=16)
    profile_picture = models.ImageField(upload_to="profile_picture", blank=True, null=True, default="default.jpg")

    def get_fullname(self):
        fullname = str(self.user.first_name) +" "+ str(self.user.last_name)
        return fullname

    def get_whatsapp_link(self):
        return "https://wa.me/"+str(self.phone_number)

    def __str__(self):
        return f'{self.user}'

    def get_absolute_url(self):
        return reverse("agent_property_list", kwargs={"id":self.id})



class Amenity(models.Model):
    name = models.CharField(verbose_name='Amenity', max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Amenities'

class Property(models.Model):
    OPTIONS = [
        ("Rent", "Rent"),
        ("Sale", "Sale"),
        ("Lease", "Lease"),
    ]

    property_name = models.CharField(verbose_name='Property Name', max_length=50, blank=False)
    price = models.DecimalField(verbose_name='Price', decimal_places=2, blank=False, max_digits=99999999999)
    property_description = models.TextField(verbose_name='Description', max_length=160)
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    date_listed = models.DateField(auto_now_add=True, blank=True)
    state = models.CharField(max_length=20, blank=True,default="Kwara")
    city = models.CharField(max_length=20, blank=True, default= "Ilorin")
    area = models.CharField(max_length=50, blank=True, default="MFM")
    address = models.CharField(max_length=50, blank=True, default="")
    status = models.CharField(choices=OPTIONS, max_length=10)
    featured = models.BooleanField(default=False)
    slug = models.SlugField(blank=True, editable=False)
    #image = models.ForeignKey(Images, on_delete=models.CASCADE)
    amenity = models.ManyToManyField(Amenity)
    no_of_plots = models.IntegerField(verbose_name="Plots", blank=True, default=2)


    class Meta:
        abstract = True
        ordering = ["date_listed"]


class Land(Property):

    def get_absolute_url(self):
        return reverse("property_detail", kwargs = {"id":self.id})

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.property_name)
        super(House, self).save(*args, **kwargs)


class House(Property):
    no_of_bedroom = models.PositiveIntegerField(verbose_name="Bed")
    no_of_bathroom = models.PositiveIntegerField(verbose_name="Bathroom", default=1, blank=True)


    def get_absolute_url(self):
        return reverse("property_detail", kwargs={"id": self.id})

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.property_name)
        super(House, self).save(*args, **kwargs)

    def __str__(self):
        return self.property_name


class Images(models.Model):
    picture = models.ImageField(upload_to='house_image', verbose_name='Picture', blank=False)
    house = models.ForeignKey(House, on_delete=models.CASCADE)

    def __str__(self):
        return self.picture.name

Blog/templates/agent_list.html
{%extends "base.html"%}
{% load static %}
{%load phonize_filter%}

 {%block content%}

  <main id="main">
    <!-- =======Intro Single ======= -->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Our Amazing Agents</h1>
              <span class="color-text-a">Grid Properties</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="{% url 'Home'%}">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  Agents Grid
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Intro Single-->

    <!-- ======= Agents Grid ======= -->
    <section class="agents-grid grid">
      <div class="container">
        <div class="row">

          {% for agent in agents %}

          <div class="col-md-4">
            <div class="card-box-d">
              <div class="card-img-d">
                <img src="{{agent.profile_picture.url}}" alt="" class="img-d img-fluid">
              </div>
              <div class="card-overlay card-overlay-hover">
                <div class="card-header-d">
                  <div class="card-title-d align-self-center">
                    <h3 class="title-d">
                      <a href="{{agent.get_absolute_url}}" class="link-two">{{ agent.user.first_name}}
                        <br> {{ agent.user.last_name}} </a>
                    </h3>
                  </div>
                </div>
                <div class="card-body-d">
                  <p class="content-d color-text-a">
                 {{ agent.about}}
                  </p>
                  <div class="info-agents color-a">
                    <p>
                      <strong>Phone: </strong>  {{agent.phone_number | phonize}}
                    </p>
                    <p>
                      <strong>Email: </strong> {{ agent.user.email}}
                    </p>
                  </div>
                </div>
                <div class="card-footer-d">
                  <div class="socials-footer d-flex justify-content-center">
                    <ul class="list-inline">
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-facebook" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-twitter" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-instagram" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-linkedin" aria-hidden="true"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {% endfor %}
        </div>
        {% include "pagination.html"%}
      </div>
    </section><!-- End Agents Grid-->

  </main><!-- End #main -->

  {%endblock content%}

Blog/templates/agent_property_list.html
{% extends "base.html"%}
{% load static%}
{%load phonize_filter%}

{%block content%}
    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">{{ agent.get_fullname}}</h1>
              <span class="color-text-a">Agent Immobiliari</span>

              {% if request.user.id == id %}

              <div class="container">
                    <a class="btn btn-outline.secondary" href="{% url 'property_create' %}">Create</a>
              </div>
              {% endif %}
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="{% url 'Home'%}">Home</a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{% url 'agent_list'%}">Agents</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  {{ agent.get_fullname}}
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Intro Single -->

    <!-- ======= Agent Single ======= -->
    <section class="agent-single">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="row">
              <div class="col-md-6">
                <div class="agent-avatar-box">
                  <img src="{{agent.profile_picture.url}}" alt="" class="agent-avatar img-fluid">
                </div>
              </div>
              <div class="col-md-5 section-md-t3">
                <div class="agent-info-box">
                  <div class="agent-title">
                    <div class="title-box-d">
                      <h3 class="title-d">{{agent.user.first_name}}
                        <br> {{agent.user.last_name}}
                      </h3>
                    </div>
                  </div>
                  <div class="agent-content mb-3">
                    <p class="content-d color-text-a">
                    {{agent.about}}

                     </p>
                    <div class="info-agents color-a">
                      <p>
                        <strong>Phone: </strong>
                        <span class="color-text-a"> {{ agent.phone_number | phonize}}</span>
                      </p>
                      <p>
                        <strong>Mobile: </strong>
                        <span class="color-text-a">{{ agent.phone_number | phonize}}</span>
                      </p>
                      <p>
                        <strong>Email: </strong>
                        <span class="color-text-a"> {{agent.user.email}}</span>
                      </p>

                      <p>
                        <strong>Address: </strong>
                        <span class="color-text-a">{{ agent.address}}</span>
                      </p>
                    </div>
                  </div>
                  <div class="socials-footer">
                    <ul class="list-inline">
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-facebook" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-twitter" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-instagram" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#" class="link-one">
                          <i class="bi bi-linkedin" aria-hidden="true"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-12 section-t8">
            <div class="title-box-d">
              <h3 class="title-d">My Properties ({{ agent_properties.count}})</h3>
            </div>
          </div>
          <div class="row property-grid grid">
            <div class="col-sm-12">
              <div class="grid-option">
                <form>
                  <select class="custom-select">
                    <option selected>All</option>
                    <option value="1">New to Old</option>
                    <option value="2">For Rent</option>
                    <option value="3">For Sale</option>
                  </select>
                </form>
              </div>
            </div>
            {% for property in agent_properties%}
            <div class="col-md-4">
              <div class="card-box-a card-shadow">
                <div class="img-box-a">
                  <img src="{{property.images_set.first.picture.url}}" alt="" class="img-a img-fluid">
                </div>
                <div class="card-overlay">
                  <div class="card-overlay-a-content">
                    <div class="card-header-a">
                      <h2 class="card-title-a">
                        <a href="{{property.get_absolute_url}}">{{property.property_name}}
                          <br /> {{ property.area}}</a>
                      </h2>
                    </div>
                    <div class="card-body-a">
                      <div class="price-box d-flex">
                        <span class="price-a">{{ property.status}} | # {{property.price}}</span>
                      </div>
                      <a href="{{property.get_absolute_url}}" class="link-a">Click here to view
                        <span class="bi bi-chevron-right"></span>
                      </a>
                    </div>
                    <div class="card-footer-a">
                      <ul class="card-info d-flex justify-content-around">
                        <li>
                          <h4 class="card-info-title">Plot</h4>
                          <span>{{property.no_of_plots}}

                          </span>
                        </li>
                        <li>
                          <h4 class="card-info-title">Beds</h4>
                          <span>{{ property.no_of_bedroom}}</span>
                        </li>
                        <li>
                          <h4 class="card-info-title">Baths</h4>
                          <span>{{property.no_of_bathroom}}</span>
                        </li>
                        <li>
                          <h4 class="card-info-title">Garages</h4>
                          <span>1</span>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            {% include "pagination.html"%}
          </div>
        </div>
      </div>



    </section><!-- End Agent Single -->

    {%endblock content%}

Blog/templates/base.html
{% load static%}

<!DOCTYPE html>
<html lang="en">

<head>
  {%include "head.html"%}
</head>

<body>
{%include "navbar.html"%}

  <main id="main">


    {% block content%}
    {%endblock content%}

  </main>

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

{% include "footer.html"%}

{% include "script.html"%}
</body>

</html>

Blog/templates/property_detail.html
{%extends 'base.html'%}
{% load static %}
{% load humanize%}
{% load phonize_filter%}

{% block content %}
    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">{{property.property_name | title}}</h1>
              <span class="color-text-a">{{property.address | title}}, {{property.area | title}} {{property.city | title}}</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="{% url 'Home'%}">Home</a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{% url 'property_list'%}">Properties</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  {{property.property_name | title}}
                </li>
              </ol>

              {% if request.user == property.agent.user%}
              <div class="container">

                <a class="btn btn-outline.danger" href="{% url 'property_delete' property.id%}">Delete</a>
                    <a class="btn btn-outline.secondary" href="{% url 'property_edit' property.id %}">Edit</a>

              </div>
              {% endif%}
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Intro Single-->

    <!-- ======= Property Single ======= -->
    <section class="property-single nav-arrow-b">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <div id="property-single-carousel" class="swiper">
              <div class="swiper-wrapper">
                {% for im in property.images_set.all%}

                <div class="carousel-item-b swiper-slide">
                  {% if im.picture %}
                  <img src="{{im.picture.url}}" alt="">
                  {% endif %}
                </div>
                {% endfor %}
              </div>
            </div>
            <div class="property-single-carousel-pagination carousel-pagination"></div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">

            <div class="row justify-content-between">
              <div class="col-md-5 col-lg-4">
                <div class="property-price d-flex justify-content-center foo">
                  <div class="card-header-c d-flex">
                    <div class="card-box-ico">
                      <span class="bi bi-cash">#</span>
                    </div>
                    <div class="card-title-c align-self-center">
                      <h5 class="title-c">{{property.price | intcomma}}</h5>
                    </div>
                  </div>
                </div>
                <div class="property-summary">
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="title-box-d section-t4">
                        <h3 class="title-d">Quick Summary</h3>
                      </div>
                    </div>
                  </div>
                  <div class="summary-list">
                    <ul class="list">
                      <li class="d-flex justify-content-between">
                        <strong>Property ID:</strong>
                        <span>{{property.id}}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Location:</strong>
                        <span>{{property.address}}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Property Type:</strong>
                        <span>House</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Status:</strong>
                        <span>{{property.status}}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Plots:</strong>
                        <span>{{property.no_of_plots}}

                        </span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Beds:</strong>
                        <span>{{property.no_of_bedroom}}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Baths:</strong>
                        <span>{{property.no_of_bathroom}}</span>
                      </li>
                      <li class="d-flex justify-content-between">
                        <strong>Garage:</strong>
                        <span>1</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-md-7 col-lg-7 section-md-t3">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="title-box-d">
                      <h3 class="title-d">Property Description</h3>
                    </div>
                  </div>
                </div>
                <div class="property-description">
                  <p class="description color-text-a">
                    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit
                    neque, auctor sit amet
                    aliquam vel, ullamcorper sit amet ligula. Cras ultricies ligula sed magna dictum porta.
                    Curabitur aliquet quam id dui posuere blandit. Mauris blandit aliquet elit, eget tincidunt
                    nibh pulvinar quam id dui posuere blandit.
                  </p>
                  <p class="description color-text-a no-margin">
                  {{property.description}}
                  </p>
                </div>
                <div class="row section-t3">
                  <div class="col-sm-12">
                    <div class="title-box-d">
                      <h3 class="title-d">Amenities</h3>
                    </div>
                  </div>
                </div>
                <div class="amenities-list color-text-a">
                  <ul class="list-a no-margin">
                    {% for a in property.amenity.all%}
                    <li>{{a.name}}</li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-12">
            <div class="row section-t3">
              <div class="col-sm-12">
                <div class="title-box-d">
                  <h3 class="title-d">Contact Agent</h3>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 col-lg-4">
                <img src="{{agent.profile_picture.url}}" alt="" class="img-fluid">
              </div>
              <div class="col-md-6 col-lg-4">
                <div class="property-agent">
                  <a href = "{{agent.get_absolute_url}}" ><h4 class="title-agent">{{ agent.get_fullname}}</h4></a>
                  <p class="color-text-a">
                  {{ agent.about}}
                    <br>
                    <br>
                    {{ agent.address}}
                  </p>
                  <ul class="list-unstyled">
                    <li class="d-flex justify-content-between">
                      <strong>Phone:</strong>
                      <span class="color-text-a">{{agent.phone_number | phonize}}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Mobile:</strong>
                      <span class="color-text-a">{{agent.phone_number|phonize}}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Email:</strong>
                      <span class="color-text-a">{{agent.user.email}}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Whatsapp:</strong>
                      <a href="{{agent.get_whatsapp_link}}"><span class="color-text-a">Message Me</span></a>
                    </li>
                  </ul>
                  <div class="socials-a">
                    <ul class="list-inline">
                      <li class="list-inline-item">
                        <a href="#">
                          <i class="bi bi-facebook" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#">
                          <i class="bi bi-twitter" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#">
                          <i class="bi bi-instagram" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href="#">
                          <i class="bi bi-linkedin" aria-hidden="true"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-md-12 col-lg-4">
                <div class="property-contact">
                  <form class="form-a">
                    <div class="row">
                      <div class="col-md-12 mb-1">
                        <div class="form-group">
                          <input type="text" class="form-control form-control-lg form-control-a" id="inputName" placeholder="Name *" required>
                        </div>
                      </div>
                      <div class="col-md-12 mb-1">
                        <div class="form-group">
                          <input type="email" class="form-control form-control-lg form-control-a" id="inputEmail1" placeholder="Email *" required>
                        </div>
                      </div>
                      <div class="col-md-12 mb-1">
                        <div class="form-group">
                          <textarea id="textMessage" class="form-control" placeholder="Comment *" name="message" cols="45" rows="8" required></textarea>
                        </div>
                      </div>
                      <div class="col-md-12 mt-3">
                        <button type="submit" class="btn btn-a">Send Message</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section><!-- End Property Single-->

  </main><!-- End #main -->
{%endblock content%}

Blog/templates/property_list.html
{%extends "base.html"%}
{% load static%}
{% load humanize %}
{%block content%}
    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Our Amazing Properties</h1>
              <span class="color-text-a">Grid Properties</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="{%url 'Home'%}">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  Properties Grid
                </li>
                  <div class="container">
                    <a class="btn btn-outline.secondary" href="{% url 'property_create' %}">Create</a>
              </div>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Intro Single-->

    <!-- ======= Property Grid ======= -->
    <section class="property-grid grid">
      <div class="container">
        <div class="row">


          {% for property in properties %}
          <div class="col-md-4">
            <div class="card-box-a card-shadow">
              <div class="img-box-a">
                <img src="{{property.images_set.first.picture.url}}" alt="" class="img-a img-fluid">
              </div>
              <div class="card-overlay">
                <div class="card-overlay-a-content">
                  <div class="card-header-a">
                    <h2 class="card-title-a">
                      <a href="{{ property.get_absolute_url }}">{{property.property_name}}
                        <br /> {{property.area}}</a>
                    </h2>
                  </div>
                  <div class="card-body-a">
                    <div class="price-box d-flex">
                      <span class="price-a">{{ property.status }} | # {{ property.price|intcomma }}</span>
                    </div>
                    <a href="{{ property.get_absolute_url }}" class="link-a">Click here to view
                      <span class="bi bi-chevron-right"></span>
                    </a>
                  </div>
                  <div class="card-footer-a">
                    <ul class="card-info d-flex justify-content-around">
                      <li>
                        <h4 class="card-info-title">Plots</h4>
                        <span>{{property.no_of_plots}}
                        </span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Beds</h4>
                        <span>{{property.no_of_bedroom}}</span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Baths</h4>
                        <span>{{ property.no_of_bathroom}}</span>
                      </li>
                      <li>
                        <h4 class="card-info-title">Garages</h4>
                        <span>1</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {%endfor%}


        </div>

        {% include "pagination.html"%}



{%endblock content%}

